task_manager/labels/urls.py
from django.urls import path

from task_manager.labels import views

app_name = 'labels'

urlpatterns = [
    path('', views.LabelListView.as_view(), name='index'),
    path('create/', views.LabelCreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.LabelUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.LabelDeleteView.as_view(), name='delete'),
]

task_manager/tasks/urls.py
from django.urls import path

from task_manager.tasks import views

app_name = 'tasks'

urlpatterns = [
    path('', views.TaskListView.as_view(), name='index'),
    path('create/', views.TaskCreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.TaskUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.TaskDeleteView.as_view(), name='delete'),
    path('<int:pk>/', views.TaskDetailView.as_view(), name='detail')
]

task_manager/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

from task_manager.views import CustomLoginView, CustomLogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('users/', include('task_manager.users.urls')),
    path('statuses/', include('task_manager.statuses.urls')),
    path('labels/', include('task_manager.labels.urls')),
    path('tasks/', include('task_manager.tasks.urls')),
]

task_manager/users/urls.py
from django.urls import path

from task_manager.users import views

app_name = 'users'

urlpatterns = [
    path('', views.UserListView.as_view(), name='index'),
    path('create/', views.UserCreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.UserUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.UserDeleteView.as_view(), name='delete'),
]

task_manager/labels/models.py
from django.db import models
from django.db.models.deletion import ProtectedError
from django.utils.translation import gettext_lazy as _


class Label(models.Model):
    name = models.CharField(
        max_length=255,
        blank=False,
        verbose_name=_('Name'),
        unique=True,
        error_messages={
            'unique': _('This label with this name already exists. '
                        'Please choose another name.'),
        }
    )
    created_at = models.DateTimeField(auto_now_add=True)

    def delete(self, *args, **kwargs):
        if self.task_set.exists():
            raise ProtectedError(
                _("Cannot delete this label because they are being used"),
                self
            )
        super().delete(*args, **kwargs)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('Label')
        verbose_name_plural = _('Labels')

task_manager/forms.py
from django.contrib.auth.forms import AuthenticationForm


class CustomLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        bs_cls = 'form-control bg-secondary bg-opacity-50 border-secondary'
        for field in self.fields.values():
            field.widget.attrs['class'] = bs_cls
            field.widget.attrs['placeholder'] = field.label

task_manager/labels/forms.py
from django.forms import ModelForm

from task_manager.labels.models import Label
from task_manager.mixins import FormStyleMixin


class LabelCreationForm(FormStyleMixin, ModelForm):
    class Meta:
        model = Label
        fields = ['name']

task_manager/statuses/forms.py
from django.forms import ModelForm

from task_manager.mixins import FormStyleMixin
from task_manager.statuses.models import Status


class StatusCreationForm(FormStyleMixin, ModelForm):
    class Meta:
        model = Status
        fields = ['name']

task_manager/tasks/forms.py
from django.forms import ModelForm

from task_manager.mixins import FormStyleMixin
from task_manager.tasks.models import Task


class TaskCreationForm(FormStyleMixin, ModelForm):
    class Meta:
        model = Task
        fields = ['name', 'description', 'status', 'executor', 'labels']

task_manager/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import gettext_lazy as _

from task_manager.mixins import FormStyleMixin
from task_manager.users.models import User


class BaseUserForm:
    """Base Meta settings for User forms."""
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username')
        help_texts = {
            'username': _(
                'Required. 150 characters or fewer. '
                'Letters, digits and @/./+/-/_ only.'
            ),
        }


class CustomUserCreationForm(FormStyleMixin, UserCreationForm):
    """User registration form with Bootstrap and password fields."""
    class Meta(BaseUserForm.Meta):
        fields = (*BaseUserForm.Meta.fields, 'password1', 'password2')
        help_texts = {
            **BaseUserForm.Meta.help_texts,
            'password1':
                _('Your password must contain at least 3 characters.'),
            'password2':
                _('Please enter your password again to confirm.'),
        }

    def clean(self):
        """Ensure passwords match and meet requirements."""
        cleaned_data = super().clean()
        password1 = cleaned_data.get("password1")
        password2 = cleaned_data.get("password2")

        if password1 and password2:
            if password1 != password2:
                self.add_error(
                    "password2",
                    _("Passwords don't match.")
                )

            if len(password1) < 3:
                self.add_error(
                    "password2",
                    _(
                        "This password is too short. "
                        "It must contain at least 3 characters."
                    ),
                )
        return cleaned_data


class CustomUserChangeForm(FormStyleMixin, forms.ModelForm):
    """User update form with password change and Bootstrap styling."""
    password1 = forms.CharField(
        label=_("New Password"),
        widget=forms.PasswordInput,
        required=True,
        help_text=_("Your password must contain at least 3 characters."),
    )
    password2 = forms.CharField(
        label=_("Confirm Password"),
        widget=forms.PasswordInput,
        required=True,
        help_text=_("Please enter your password again to confirm."),
    )

    class Meta(BaseUserForm.Meta):
        fields = (*BaseUserForm.Meta.fields, 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if 'password' in self.fields:
            del self.fields['password']

    def clean(self):
        """Ensure passwords match."""
        cleaned_data = super().clean()
        password1 = cleaned_data.get("password1")
        password2 = cleaned_data.get("password2")

        if password1 and password2:
            if password1 != password2:
                self.add_error(
                    "password2",
                    _("Passwords don't match.")
                )
            elif len(password1) < 3:
                self.add_error(
                    "password2",
                    _(
                        "This password is too short. "
                        "It must contain at least 3 characters."
                    ),
                )
        return cleaned_data

    def save(self, commit=True):
        user = super().save(commit=False)
        if password1 := self.cleaned_data.get("password1"):
            user.set_password(password1)
        if commit:
            user.save()
        return user

task_manager/labels/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import (
    CreateView,
    DeleteView,
    ListView,
    UpdateView,
)

from task_manager.labels.forms import LabelCreationForm
from task_manager.labels.models import Label
from task_manager.mixins import (
    CustomLoginRequiredMixin,
    ProtectErrorMixin,
)

URL_INDEX = 'labels:index'


class LabelListView(CustomLoginRequiredMixin, ListView):
    model = Label
    template_name = 'labels/index.html'
    context_object_name = 'labels'
    ordering = ['id']


class LabelCreateView(CustomLoginRequiredMixin,
                      SuccessMessageMixin,
                      CreateView):
    model = Label
    template_name = 'labels/label_form.html'
    form_class = LabelCreationForm
    success_url = reverse_lazy(URL_INDEX)
    success_message = _('Label was created successfully')
    extra_context = {
        'title': _('Create label'),
        'button_name': _('Create')
    }


class LabelUpdateView(CustomLoginRequiredMixin,
                      SuccessMessageMixin,
                      UpdateView):
    form_class = LabelCreationForm
    model = Label
    template_name = 'labels/label_form.html'
    success_url = reverse_lazy(URL_INDEX)
    success_message = _('Label was updated successfully')
    extra_context = {
        'title': _('Update label'),
        'button_name': _('Update')
    }


class LabelDeleteView(CustomLoginRequiredMixin,
                      SuccessMessageMixin,
                      ProtectErrorMixin,
                      DeleteView):
    template_name = 'labels/label_delete.html'
    model = Label
    success_url = reverse_lazy(URL_INDEX)
    success_message = _('Label was deleted successfully')
    protected_object_url = reverse_lazy(URL_INDEX)
    protected_object_message = _(
        'Cannot delete this label because they are being used'
    )
    extra_context = {
        'title': _('Label deletion'),
        'button_name': _('Yes, delete')
    }

task_manager/statuses/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import (
    CreateView,
    DeleteView,
    ListView,
    UpdateView,
)

from task_manager.mixins import (
    CustomLoginRequiredMixin,
    ProtectErrorMixin,
)
from task_manager.statuses.forms import StatusCreationForm
from task_manager.statuses.models import Status

URL_INDEX = 'statuses:index'


class StatusListView(CustomLoginRequiredMixin, ListView):
    model = Status
    template_name = 'statuses/index.html'
    context_object_name = 'statuses'
    ordering = ['id']


class StatusCreateView(CustomLoginRequiredMixin,
                       SuccessMessageMixin,
                       CreateView):
    model = Status
    template_name = 'statuses/status_form.html'
    form_class = StatusCreationForm
    success_url = reverse_lazy(URL_INDEX)
    success_message = _('Status was created successfully')
    extra_context = {
        'title': _('Create status'),
        'button_name': _('Create')
    }


class StatusUpdateView(CustomLoginRequiredMixin,
                       SuccessMessageMixin,
                       UpdateView):
    form_class = StatusCreationForm
    model = Status
    template_name = 'statuses/status_form.html'
    success_url = reverse_lazy(URL_INDEX)
    success_message = _('Status was updated successfully')
    extra_context = {
        'title': _('Update status'),
        'button_name': _('Update')
    }


class StatusDeleteView(CustomLoginRequiredMixin,
                       SuccessMessageMixin,
                       ProtectErrorMixin,
                       DeleteView):
    template_name = 'statuses/status_delete.html'
    model = Status
    success_url = reverse_lazy(URL_INDEX)
    success_message = _('Status was deleted successfully')
    protected_object_url = reverse_lazy(URL_INDEX)
    protected_object_message = _(
        'Cannot delete this status because they are being used'
    )
    extra_context = {
        'title': _('Status deletion'),
        'button_name': _('Yes, delete')
    }

task_manager/tasks/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import CreateView, DeleteView, DetailView, UpdateView
from django_filters.views import FilterView

from task_manager.mixins import AuthorPermissionMixin, CustomLoginRequiredMixin
from task_manager.tasks.filters import TaskFilter
from task_manager.tasks.forms import TaskCreationForm
from task_manager.tasks.models import Task

URL_INDEX = 'tasks:index'


class TaskListView(CustomLoginRequiredMixin, FilterView):
    model = Task
    template_name = 'tasks/index.html'
    filterset_class = TaskFilter
    context_object_name = 'tasks'
    ordering = 'id'


class TaskDetailView(CustomLoginRequiredMixin, DetailView):
    model = Task
    template_name = 'tasks/detail.html'
    context_object_name = 'task'


class TaskCreateView(CustomLoginRequiredMixin,
                     SuccessMessageMixin,
                     CreateView):
    model = Task
    template_name = 'tasks/task_form.html'
    form_class = TaskCreationForm
    success_url = reverse_lazy(URL_INDEX)
    success_message = _('Task was created successfully')
    extra_context = {
        'title': _('Create task'),
        'button_name': _('Create')
    }

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class TaskUpdateView(CustomLoginRequiredMixin,
                     SuccessMessageMixin,
                     UpdateView):
    model = Task
    template_name = 'tasks/task_form.html'
    form_class = TaskCreationForm
    success_url = reverse_lazy(URL_INDEX)
    success_message = _('Task was updated successfully')
    extra_context = {
        'button_name': _('Update'),
        'title': _('Update task')
    }


class TaskDeleteView(CustomLoginRequiredMixin,
                     AuthorPermissionMixin,
                     SuccessMessageMixin,
                     DeleteView):
    model = Task
    template_name = 'tasks/delete.html'
    success_url = reverse_lazy(URL_INDEX)
    success_message = _('Task was deleted successfully')
    permission_denied_url = reverse_lazy(URL_INDEX)
    permission_denied_message = _("Only the task's author can delete it")
    extra_context = {
        'title': _('Task deletion'),
        'button_name': _('Yes, delete')
    }

task_manager/users/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import (
    CreateView,
    DeleteView,
    ListView,
    UpdateView,
)

from task_manager.mixins import (
    CustomLoginRequiredMixin,
    ProtectErrorMixin,
    UserPermissionMixin,
)
from task_manager.users.forms import (
    CustomUserChangeForm,
    CustomUserCreationForm,
)
from task_manager.users.models import User

URL_INDEX = 'users:index'
ERROR_MESSAGE_NO_RIGHTS = _("You don't have rights to change another user.")


class UserListView(ListView):
    model = User
    template_name = 'users/index.html'
    context_object_name = 'users'
    ordering = ['id']


class BaseUserView(SuccessMessageMixin):
    model = User
    template_name = 'users/registration_form.html'
    context_object_name = 'user'
    permission_denied_url = reverse_lazy('users:index')


class UserCreateView(BaseUserView, CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy("login")
    success_message = _('User was registered successfully')
    extra_context = {
        'title': _('Sign Up'),
        'button_name': _('Register')
    }


class UserUpdateView(CustomLoginRequiredMixin, UserPermissionMixin,
                     BaseUserView, UpdateView):
    form_class = CustomUserChangeForm
    success_url = reverse_lazy(URL_INDEX)
    success_message = _('User was updated successfully')
    permission_denied_message = ERROR_MESSAGE_NO_RIGHTS
    extra_context = {
        'title': _('Edit profile'),
        'button_name': _('Save changes')
    }


class UserDeleteView(CustomLoginRequiredMixin, UserPermissionMixin,
                     ProtectErrorMixin, BaseUserView, DeleteView):
    template_name = 'users/user_delete.html'
    success_url = reverse_lazy(URL_INDEX)
    success_message = _('User was deleted successfully')
    permission_denied_message = ERROR_MESSAGE_NO_RIGHTS
    access_denied_message = ERROR_MESSAGE_NO_RIGHTS
    protected_object_url = reverse_lazy(URL_INDEX)
    protected_object_message = _(
        'Cannot delete this user because they are being used'
    )
    extra_context = {
        'title': _('User deletion'),
        'button_name': _('Yes, delete')
    }

task_manager/views.py
from django.contrib import messages
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

from task_manager.forms import CustomLoginForm


class CustomLoginView(SuccessMessageMixin, LoginView):
    template_name = 'login_form.html'
    form_class = CustomLoginForm
    next_page = reverse_lazy('index')
    success_message = _('You were logged in')


class CustomLogoutView(SuccessMessageMixin, LogoutView):
    next_page = reverse_lazy('index')

    def dispatch(self, request, *args, **kwargs):
        messages.info(request, _('You were logged out'))
        return super().dispatch(request, *args, **kwargs)

task_manager/templates/labels/create.html
{% extends 'base.html' %}
{% load i18n %}
{% load django_bootstrap5 %}
{% block content %}
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="{% translate 'Create' %}">
</form>
{% endblock %}

task_manager/templates/labels/delete.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}


<form method="post">
    {% csrf_token %}
    <input type="submit" value="{% translate 'Confirm delete' %}">
</form>
{% endblock %}

task_manager/templates/labels/index.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Labels" %}{% endblock %}
{% block main_classes %}container py-5{% endblock %}

{% block content %}
<div class="row">
  <div class="col-12">
    <h1 class="mb-3">{% trans "Labels" %}</h1>
    <div class="mb-4">
      <a href="{% url 'labels:create' %}" class="btn btn-outline-success">
        {% trans "Create label" %}
      </a>
    </div>
    {% if labels %}
      <div class="table-responsive">
        <table class="table table-dark table-striped table-borderless align-middle mb-0">
          <thead class="align-middle">
            <tr>
              <th scope="col">ID</th>
              <th scope="col">{% trans "Name" %}</th>
              <th scope="col" class="text-end text-nowrap">{% trans "Date created" %}</th>
              <th scope="col" class="text-center"></th>
            </tr>
          </thead>
          <tbody>
            {% for label in labels %}
              <tr>
                <td>{{ label.id }}</td>
                <td>{{ label.name }}</td>
                <td class="text-end text-nowrap">{{ label.created_at|date:"d.m.Y H:i" }}</td>
                <td class="text-center">
                  <div class="d-inline-flex flex-wrap justify-content-center gap-2">
                    <a href="{% url 'labels:update' label.id %}" class="btn btn-sm btn-outline-light">
                      {% trans "Edit" %}
                    </a>
                    <a href="{% url 'labels:delete' label.id %}" class="btn btn-sm btn-outline-danger">
                      {% trans "Delete" %}
                    </a>
                  </div>
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    {% else %}
      <div class="text-white">
        {% trans "No labels found." %}
      </div>
    {% endif %}
  </div>
</div>
{% endblock %}

task_manager/templates/labels/label_delete.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{{ title }}{% endblock %}
{% block main_classes %}container wrapper flex-grow-1{% endblock %}

{% block content %}
<div class="my-4">
  <h1>{{ title }}</h1>
  <form method="post" class="mt-3">
    {% csrf_token %}
    {% for field in form %}
      <div class="mb-3">
        <label for="{{ field.id_for_label }}" class="form-label text-white">
          {{ field.label }}
        </label>
        {{ field }}
        {% if field.errors %}
          <div class="invalid-feedback d-block text-danger">
            {% for error in field.errors %}
              {{ error }}
            {% endfor %}
          </div>
        {% endif %}
      </div>
    {% endfor %}
    <p class="fs-5">
        {% trans 'Are you sure you want to delete' %} {{ label.name }}?
      </p>
    <button type="submit" class="btn btn-outline-danger">
      {{ button_name }}
    </button>
  </form>
</div>
{% endblock %}

task_manager/templates/labels/label_form.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{{ title }}{% endblock %}
{% block main_classes %}container wrapper flex-grow-1{% endblock %}

{% block content %}
<div class="my-4">
  <h1>{{ title }}</h1>
  <form method="post" class="mt-3">
    {% csrf_token %}
    {% for field in form %}
      <div class="mb-3">
        <label for="{{ field.id_for_label }}" class="form-label text-white">
          {{ field.label }}
        </label>
        {{ field }}
        {% if field.help_text %}
          <div class="form-text text-white-50">
            {{ field.help_text }}
          </div>
        {% endif %}
        {% if field.errors %}
          <div class="invalid-feedback d-block text-danger">
            {% for error in field.errors %}
              {{ error }}
            {% endfor %}
          </div>
        {% endif %}
      </div>
    {% endfor %}
    <button type="submit" class="btn btn-outline-success">
      {{ button_name }}
    </button>
  </form>
</div>
{% endblock %}

task_manager/templates/labels/list.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}


<h1 class="my-4">
        
    {% translate 'Labels' %}
    
          </h1>
          
    <a class="btn btn-primary mb-3" href="{% url 'labels:create' %}">{% translate 'Create label' %}</a>
    <table class="table table-striped">
        <thead>
          <tr>
            <th>{% translate 'ID' %}</th>
            <th>{% translate 'Name' %}</th>
            <th>{% translate 'Creation Date' %}</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {% for label in labels_list %}
          <tr>
            <td>{{ label.id }}</td>
            <td>{{ label.name }}</td>
            <td>{{ label.created_at }}</td>
            <td>
              <a href="{% url 'labels:update' label.id%}">{% translate 'Edit' %}</a>
              <br>
              <a href="{% url 'labels:delete' label.id %}">{% translate 'Delete' %}</a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      
{% endblock %}
      

task_manager/templates/labels/update.html
{% extends "base.html" %}
{% load i18n %}
{% load django_bootstrap5 %}
{% block content %}
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="{% translate 'Update' %}">
</form>
{% endblock %}