task_manager/labels/urls.py
from django.urls import path

from task_manager.labels import views

app_name = 'labels'

urlpatterns = [
    path('', views.LabelListView.as_view(), name='index'),
    path('create/', views.LabelCreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.LabelUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.LabelDeleteView.as_view(), name='delete'),
]

task_manager/tasks/urls.py
from django.urls import path

from task_manager.tasks import views

app_name = 'tasks'

urlpatterns = [
    path('', views.TaskListView.as_view(), name='index'),
    path('create/', views.TaskCreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.TaskUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.TaskDeleteView.as_view(), name='delete'),
    path('<int:pk>/', views.TaskDetailView.as_view(), name='detail')
]

task_manager/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

from task_manager.views import CustomLoginView, CustomLogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('users/', include('task_manager.users.urls')),
    path('statuses/', include('task_manager.statuses.urls')),
    path('labels/', include('task_manager.labels.urls')),
    path('tasks/', include('task_manager.tasks.urls')),
]

task_manager/users/urls.py
from django.urls import path

from task_manager.users import views

app_name = 'users'

urlpatterns = [
    path('', views.UserListView.as_view(), name='index'),
    path('create/', views.UserCreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.UserUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.UserDeleteView.as_view(), name='delete'),
]

task_manager/labels/models.py
from django.db import models
from django.db.models.deletion import ProtectedError
from django.utils.translation import gettext_lazy as _


class Label(models.Model):
    name = models.CharField(
        max_length=255,
        blank=False,
        verbose_name=_('Name'),
        unique=True,
        error_messages={
            'unique': _('This label with this name already exists. '
                        'Please choose another name.'),
        }
    )
    created_at = models.DateTimeField(auto_now_add=True)

    def delete(self, *args, **kwargs):
        if self.task_set.exists():
            raise ProtectedError(
                _("Cannot delete this label because they are being used"),
                self
            )
        super().delete(*args, **kwargs)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('Label')
        verbose_name_plural = _('Labels')

task_manager/forms.py
from django.contrib.auth.forms import AuthenticationForm


class CustomLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        bs_cls = 'form-control bg-secondary bg-opacity-50 border-secondary'
        for field in self.fields.values():
            field.widget.attrs['class'] = bs_cls
            field.widget.attrs['placeholder'] = field.label

task_manager/labels/forms.py
from django.forms import ModelForm

from task_manager.labels.models import Label
from task_manager.mixins import FormStyleMixin


class LabelCreationForm(FormStyleMixin, ModelForm):
    class Meta:
        model = Label
        fields = ['name']

task_manager/statuses/forms.py
from django.forms import ModelForm

from task_manager.mixins import FormStyleMixin
from task_manager.statuses.models import Status


class StatusCreationForm(FormStyleMixin, ModelForm):
    class Meta:
        model = Status
        fields = ['name']

task_manager/tasks/forms.py
from django.forms import ModelForm

from task_manager.mixins import FormStyleMixin
from task_manager.tasks.models import Task


class TaskCreationForm(FormStyleMixin, ModelForm):
    class Meta:
        model = Task
        fields = ['name', 'description', 'status', 'executor', 'labels']

task_manager/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import gettext_lazy as _

from task_manager.mixins import FormStyleMixin
from task_manager.users.models import User


class BaseUserForm:
    """Base Meta settings for User forms."""
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username')
        help_texts = {
            'username': _(
                'Required. 150 characters or fewer. '
                'Letters, digits and @/./+/-/_ only.'
            ),
        }


class CustomUserCreationForm(FormStyleMixin, UserCreationForm):
    """User registration form with Bootstrap and password fields."""
    class Meta(BaseUserForm.Meta):
        fields = (*BaseUserForm.Meta.fields, 'password1', 'password2')
        help_texts = {
            **BaseUserForm.Meta.help_texts,
            'password1':
                _('Your password must contain at least 3 characters.'),
            'password2':
                _('Please enter your password again to confirm.'),
        }

    def clean(self):
        """Ensure passwords match and meet requirements."""
        cleaned_data = super().clean()
        password1 = cleaned_data.get("password1")
        password2 = cleaned_data.get("password2")

        if password1 and password2:
            if password1 != password2:
                self.add_error(
                    "password2",
                    _("Passwords don't match.")
                )

            if len(password1) < 3:
                self.add_error(
                    "password2",
                    _(
                        "This password is too short. "
                        "It must contain at least 3 characters."
                    ),
                )
        return cleaned_data


class CustomUserChangeForm(FormStyleMixin, forms.ModelForm):
    """User update form with password change and Bootstrap styling."""
    password1 = forms.CharField(
        label=_("New Password"),
        widget=forms.PasswordInput,
        required=True,
        help_text=_("Your password must contain at least 3 characters."),
    )
    password2 = forms.CharField(
        label=_("Confirm Password"),
        widget=forms.PasswordInput,
        required=True,
        help_text=_("Please enter your password again to confirm."),
    )

    class Meta(BaseUserForm.Meta):
        fields = (*BaseUserForm.Meta.fields, 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if 'password' in self.fields:
            del self.fields['password']

    def clean(self):
        """Ensure passwords match."""
        cleaned_data = super().clean()
        password1 = cleaned_data.get("password1")
        password2 = cleaned_data.get("password2")

        if password1 and password2:
            if password1 != password2:
                self.add_error(
                    "password2",
                    _("Passwords don't match.")
                )
            elif len(password1) < 3:
                self.add_error(
                    "password2",
                    _(
                        "This password is too short. "
                        "It must contain at least 3 characters."
                    ),
                )
        return cleaned_data

    def save(self, commit=True):
        user = super().save(commit=False)
        if password1 := self.cleaned_data.get("password1"):
            user.set_password(password1)
        if commit:
            user.save()
        return user

task_manager/labels/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import (
    CreateView,
    DeleteView,
    ListView,
    UpdateView,
)

from task_manager.labels.forms import LabelCreationForm
from task_manager.labels.models import Label
from task_manager.mixins import (
    CustomLoginRequiredMixin,
    ProtectErrorMixin,
)

URL_INDEX = 'labels:index'


class LabelListView(CustomLoginRequiredMixin, ListView):
    model = Label
    template_name = 'labels/index.html'
    context_object_name = 'labels'
    ordering = ['id']


class LabelCreateView(CustomLoginRequiredMixin,
                      SuccessMessageMixin,
                      CreateView):
    model = Label
    template_name = 'labels/label_form.html'
    form_class = LabelCreationForm
    success_url = reverse_lazy(URL_INDEX)
    success_message = _('Label was created successfully')
    extra_context = {
        'title': _('Create label'),
        'button_name': _('Create')
    }


class LabelUpdateView(CustomLoginRequiredMixin,
                      SuccessMessageMixin,
                      UpdateView):
    form_class = LabelCreationForm
    model = Label
    template_name = 'labels/label_form.html'
    success_url = reverse_lazy(URL_INDEX)
    success_message = _('Label was updated successfully')
    extra_context = {
        'title': _('Update label'),
        'button_name': _('Update')
    }


class LabelDeleteView(CustomLoginRequiredMixin,
                      SuccessMessageMixin,
                      ProtectErrorMixin,
                      DeleteView):
    template_name = 'labels/label_delete.html'
    model = Label
    success_url = reverse_lazy(URL_INDEX)
    success_message = _('Label was deleted successfully')
    protected_object_url = reverse_lazy(URL_INDEX)
    protected_object_message = _(
        'Cannot delete this label because they are being used'
    )
    extra_context = {
        'title': _('Label deletion'),
        'button_name': _('Yes, delete')
    }

task_manager/statuses/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import (
    CreateView,
    DeleteView,
    ListView,
    UpdateView,
)

from task_manager.mixins import (
    CustomLoginRequiredMixin,
    ProtectErrorMixin,
)
from task_manager.statuses.forms import StatusCreationForm
from task_manager.statuses.models import Status

URL_INDEX = 'statuses:index'


class StatusListView(CustomLoginRequiredMixin, ListView):
    model = Status
    template_name = 'statuses/index.html'
    context_object_name = 'statuses'
    ordering = ['id']


class StatusCreateView(CustomLoginRequiredMixin,
                       SuccessMessageMixin,
                       CreateView):
    model = Status
    template_name = 'statuses/status_form.html'
    form_class = StatusCreationForm
    success_url = reverse_lazy(URL_INDEX)
    success_message = _('Status was created successfully')
    extra_context = {
        'title': _('Create status'),
        'button_name': _('Create')
    }


class StatusUpdateView(CustomLoginRequiredMixin,
                       SuccessMessageMixin,
                       UpdateView):
    form_class = StatusCreationForm
    model = Status
    template_name = 'statuses/status_form.html'
    success_url = reverse_lazy(URL_INDEX)
    success_message = _('Status was updated successfully')
    extra_context = {
        'title': _('Update status'),
        'button_name': _('Update')
    }


class StatusDeleteView(CustomLoginRequiredMixin,
                       SuccessMessageMixin,
                       ProtectErrorMixin,
                       DeleteView):
    template_name = 'statuses/status_delete.html'
    model = Status
    success_url = reverse_lazy(URL_INDEX)
    success_message = _('Status was deleted successfully')
    protected_object_url = reverse_lazy(URL_INDEX)
    protected_object_message = _(
        'Cannot delete this status because they are being used'
    )
    extra_context = {
        'title': _('Status deletion'),
        'button_name': _('Yes, delete')
    }

task_manager/tasks/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import CreateView, DeleteView, DetailView, UpdateView
from django_filters.views import FilterView

from task_manager.mixins import AuthorPermissionMixin, CustomLoginRequiredMixin
from task_manager.tasks.filters import TaskFilter
from task_manager.tasks.forms import TaskCreationForm
from task_manager.tasks.models import Task

URL_INDEX = 'tasks:index'


class TaskListView(CustomLoginRequiredMixin, FilterView):
    model = Task
    template_name = 'tasks/index.html'
    filterset_class = TaskFilter
    context_object_name = 'tasks'
    ordering = 'id'


class TaskDetailView(CustomLoginRequiredMixin, DetailView):
    model = Task
    template_name = 'tasks/detail.html'
    context_object_name = 'task'


class TaskCreateView(CustomLoginRequiredMixin,
                     SuccessMessageMixin,
                     CreateView):
    model = Task
    template_name = 'tasks/task_form.html'
    form_class = TaskCreationForm
    success_url = reverse_lazy(URL_INDEX)
    success_message = _('Task was created successfully')
    extra_context = {
        'title': _('Create task'),
        'button_name': _('Create')
    }

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class TaskUpdateView(CustomLoginRequiredMixin,
                     SuccessMessageMixin,
                     UpdateView):
    model = Task
    template_name = 'tasks/task_form.html'
    form_class = TaskCreationForm
    success_url = reverse_lazy(URL_INDEX)
    success_message = _('Task was updated successfully')
    extra_context = {
        'button_name': _('Update'),
        'title': _('Update task')
    }


class TaskDeleteView(CustomLoginRequiredMixin,
                     AuthorPermissionMixin,
                     SuccessMessageMixin,
                     DeleteView):
    model = Task
    template_name = 'tasks/delete.html'
    success_url = reverse_lazy(URL_INDEX)
    success_message = _('Task was deleted successfully')
    permission_denied_url = reverse_lazy(URL_INDEX)
    permission_denied_message = _("Only the task's author can delete it")
    extra_context = {
        'title': _('Task deletion'),
        'button_name': _('Yes, delete')
    }

task_manager/users/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import (
    CreateView,
    DeleteView,
    ListView,
    UpdateView,
)

from task_manager.mixins import (
    CustomLoginRequiredMixin,
    ProtectErrorMixin,
    UserPermissionMixin,
)
from task_manager.users.forms import (
    CustomUserChangeForm,
    CustomUserCreationForm,
)
from task_manager.users.models import User

URL_INDEX = 'users:index'
ERROR_MESSAGE_NO_RIGHTS = _("You don't have rights to change another user.")


class UserListView(ListView):
    model = User
    template_name = 'users/index.html'
    context_object_name = 'users'
    ordering = ['id']


class BaseUserView(SuccessMessageMixin):
    model = User
    template_name = 'users/registration_form.html'
    context_object_name = 'user'
    permission_denied_url = reverse_lazy('users:index')


class UserCreateView(BaseUserView, CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy("login")
    success_message = _('User was registered successfully')
    extra_context = {
        'title': _('Sign Up'),
        'button_name': _('Register')
    }


class UserUpdateView(CustomLoginRequiredMixin, UserPermissionMixin,
                     BaseUserView, UpdateView):
    form_class = CustomUserChangeForm
    success_url = reverse_lazy(URL_INDEX)
    success_message = _('User was updated successfully')
    permission_denied_message = ERROR_MESSAGE_NO_RIGHTS
    extra_context = {
        'title': _('Edit profile'),
        'button_name': _('Save changes')
    }


class UserDeleteView(CustomLoginRequiredMixin, UserPermissionMixin,
                     ProtectErrorMixin, BaseUserView, DeleteView):
    template_name = 'users/user_delete.html'
    success_url = reverse_lazy(URL_INDEX)
    success_message = _('User was deleted successfully')
    permission_denied_message = ERROR_MESSAGE_NO_RIGHTS
    access_denied_message = ERROR_MESSAGE_NO_RIGHTS
    protected_object_url = reverse_lazy(URL_INDEX)
    protected_object_message = _(
        'Cannot delete this user because they are being used'
    )
    extra_context = {
        'title': _('User deletion'),
        'button_name': _('Yes, delete')
    }

task_manager/views.py
from django.contrib import messages
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

from task_manager.forms import CustomLoginForm


class CustomLoginView(SuccessMessageMixin, LoginView):
    template_name = 'login_form.html'
    form_class = CustomLoginForm
    next_page = reverse_lazy('index')
    success_message = _('You were logged in')


class CustomLogoutView(SuccessMessageMixin, LogoutView):
    next_page = reverse_lazy('index')

    def dispatch(self, request, *args, **kwargs):
        messages.info(request, _('You were logged out'))
        return super().dispatch(request, *args, **kwargs)

task_manager/templates/tasks/click.html
{% extends 'base.html' %}
{% load i18n %}
{% load django_bootstrap5 %}
{% block content %}


<div class="container wrapper flex-grow-1">
      


    <h1 class="my-4">
      
{% translate 'View task' %}
    </h1>
    
<div class="card">
<div class="card-header bg-secondary text-white">
  <h2>{{ tasks.name }}</h2>
</div>
<div class="card-body bg-light">
  <p>{{ tasks.description }}</p>
  <hr>
  <div class="container">
    <div class="row p-1">
      <div class="col">{% translate 'Creator' %}</div>
      <div class="col">{{tasks.creator}}</div>
    </div>
    <div class="row p-1">
      <div class="col">{% translate 'Executor' %}</div>
      <div class="col">{{tasks.executor}}</div>
    </div>
    <div class="row p-1">
      <div class="col">{% translate 'Status' %}</div>
      <div class="col">{{tasks.status}}</div>
    </div>
    <div class="row p-1">
      <div class="col">{% translate 'created at' %}</div>
      <div class="col">{{tasks.created_at}}</div>
    </div>
    <div class="row p-1">
      <div class="col">
        <h6>{% translate 'Labels' %}:</h6>
        <ul>
          {% for label in tasks.labels.all %}
            
          <li>{{label}}</li>
          {% endfor %}
        </ul>
      </div>
    </div>
    <div class="row p-1">
      <div class="col">
        <a href="{% url 'tasks:update' tasks.id %}">{% translate 'Update' %}</a>
        <br>
        <a href="{% url 'tasks:delete' tasks.id %}">{% translate 'Delete' %}</a>
      </div>
    </div>
  </div>
</div>
</div>

{% endblock %}

task_manager/templates/tasks/create.html
{% extends 'base.html' %}
{% load i18n %}
{% load django_bootstrap5 %}
{% block content %}
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="{% translate 'Create' %}">
</form>
{% endblock %}

task_manager/templates/tasks/delete.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{{ title }}{% endblock %}
{% block main_classes %}container wrapper flex-grow-1{% endblock %}

{% block content %}
<div class="my-4">
  <h1>{{ title }}</h1>
  <form method="post" class="mt-3">
    {% csrf_token %}
    {% for field in form %}
      <div class="mb-3">
        <label for="{{ field.id_for_label }}" class="form-label text-white">
          {{ field.label }}
        </label>
        {{ field }}
        {% if field.errors %}
          <div class="invalid-feedback d-block text-danger">
            {% for error in field.errors %}
              {{ error }}
            {% endfor %}
          </div>
        {% endif %}
      </div>
    {% endfor %}
    <p class="fs-5">
        {% trans 'Are you sure you want to delete' %} {{ task.name }}?
      </p>
    <button type="submit" class="btn btn-outline-danger">
      {{ button_name }}
    </button>
  </form>
</div>
{% endblock %}

task_manager/templates/tasks/detail.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}
  {% trans 'Task View' %}
{% endblock %}

{% block main_classes %}flex-grow-1 align-items-center justify-content-center py-5{% endblock %}

{% block content %}
<div class="container wrapper flex-grow-1">
  <h1 class="my-4 text-white">{% trans "Task View" %}</h1>

  <div class="card shadow border border-secondary rounded bg-dark text-white border-dark">
    <div class="card-header bg-secondary text-white rounded-top">
      <h2 class="h3 mb-2">{{ task.name }}</h2>
    </div>
    <div class="card-body bg-dark text-white rounded-bottom">
      <p>{{ task.description }}</p>
      <hr>
      <div class="container">
        <div class="row py-1">
          <div class="col-sm-4 fw-semibold">{% trans "Author" %}</div>
          <div class="col-sm-8">{{ task.author }}</div>
        </div>
        <div class="row py-1">
          <div class="col-sm-4 fw-semibold">{% trans "Executor" %}</div>
          <div class="col-sm-8">{{ task.executor }}</div>
        </div>
        <div class="row py-1">
          <div class="col-sm-4 fw-semibold">{% trans "Status" %}</div>
          <div class="col-sm-8">{{ task.status }}</div>
        </div>
        <div class="row py-1">
          <div class="col-sm-4 fw-semibold">{% trans "Date created" %}</div>
          <div class="col-sm-8">{{ task.created_at|date:"d.m.Y H:i" }}</div>
        </div>

        <div class="row py-3">
          <div class="col">
            <h6>{% trans "Labels" %}:</h6>
            {% if task.labels.all %}
              <ul class="mb-0">
                {% for label in task.labels.all %}
                  <li>{{ label }}</li>
                {% endfor %}
              </ul>
            {% else %}
              <p class="fst-italic">{% trans "No labels found." %}</p>
            {% endif %}
          </div>
        </div>

        <div class="row">
          <div class="col">
            <a href="{% url 'tasks:update' task.id %}" class="btn btn-outline-light btn-sm me-2">{% trans "Edit" %}</a>
            <a href="{% url 'tasks:delete' task.id %}" class="btn btn-outline-danger btn-sm">{% trans "Delete" %}</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

task_manager/templates/tasks/index.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load i18n %}

{% block title %}
  {% trans 'Tasks' %}
{% endblock %}

{% block content %}
  <div class="w-100">
    <div class="col-12">
        <h1 class="mb-3">{% trans "Tasks" %}</h1>
        <div class="mb-3">
        <a href="{% url 'tasks:create' %}" class="btn btn-outline-success">
            {% trans "Create task" %}
        </a>
    </div>
    <div class="card bg-dark text-white border-dark mb-3">
      <div class="card-body p-0">
        <form method="get" class="mb-0">
          {% bootstrap_form filter.form field_class="bg-dark text-white border-secondary" %}
          <button type="submit" class="btn btn-outline-light">{% trans 'Show results' %}</button>
        </form>
      </div>
    </div>
    <div class="table-responsive">
      <table class="table table-dark table-striped table-borderless align-middle mb-0">
        <thead class="align-middle">
          <tr class="border-top border-light border-opacity-25 shadow-sm"> 
            <th scope="col" class="pt-3">ID</th>
            <th scope="col" class="pt-3">{% trans 'Name' %}</th>
            <th scope="col" class="pt-3">{% trans 'Status' %}</th>
            <th scope="col" class="pt-3">{% trans 'Author' %}</th>
            <th scope="col" class="pt-3">{% trans 'Executor' %}</th>
            <th scope="col" class="pt-3">{% trans 'Date created' %}</th>
            <th scope="col" class="text-center pt-3"></th>
          </tr>
        </thead>
        <tbody>
          {% for task in tasks %}
            <tr>
              <td>{{ task.id }}</td>
              <td>
                <a href="{% url 'tasks:detail' task.id %}" class="link-light text-decoration-underline">
                  {{ task.name }}
                </a>
              </td>
              <td>{{ task.status }}</td>
              <td>{{ task.author }}</td>
              <td>{{ task.executor }}</td>
              <td>{{ task.created_at|date:"d.m.Y H:i" }}</td>
              <td class="text-center">
                <div class="d-inline-flex flex-wrap justify-content-center gap-2">
                  <a href="{% url 'tasks:update' task.id %}" class="btn btn-sm btn-outline-light">
                    {% trans "Edit" %}
                  </a>
                  <a href="{% url 'tasks:delete' task.id %}" class="btn btn-sm btn-outline-danger">
                    {% trans "Delete" %}
                  </a>
                </div>
              </td>
            </tr>
          {% empty %}
            <tr>
              <td colspan="7" class="text-center text-white">{% trans "No tasks found." %}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
{% endblock %}

task_manager/templates/tasks/list.html
{% extends 'base.html' %}
{% load i18n %}
{% load django_bootstrap5 %}

{% block content %}
<h1 class="my-4">
    {% translate 'Tasks' %}
</h1>

<!-- Форма фильтрации -->
<form method="get" class="filter-form mb-4">
  <div class="form-group">
      {% bootstrap_field filter.form.status %}
  </div>
  <div class="form-group">
      {% bootstrap_field filter.form.task_label %}
  </div>
  <div class="form-group">
      {% bootstrap_field filter.form.executor %}
  </div>

  <div class="form-group">
    {% bootstrap_field filter.form.own_tasks %}
</div>

  <div>
      <button type="submit" class="btn btn-primary">{% translate 'Show' %}</button>
      <a href="{% url 'tasks:list' %}" class="btn btn-secondary">{% translate 'reset filtres' %}</a>
  </div>
</form>
    <a class="btn btn-primary mb-3" href="{% url 'tasks:create' %}">{% translate 'Create task' %}</a>
    <table class="table table-striped">
        <thead>
          <tr>
            <th>{% translate 'ID' %}</th>
            <th>{% translate 'Name' %}</th>
            <th>{% translate 'Creation Date' %}</th>
            <th>{% translate 'Executor' %}</th>
            <th>{% translate 'Creator' %}</th>
            <th>{% translate 'Status' %}</th>
          </tr>
        </thead>
        <tbody>
          {% for task in tasks_list %}
          <tr>
            <td>{{ task.id }}</td>
            <td> <a href="{% url 'tasks:click' task.id %}">{{ task.name }}</a></td>
            <td>{{ task.created_at }}</td>
            <td>{{ task.executor }}</td>
            <td>{{ task.creator }}</td>
            <td>{{ task.status }}</td>
            <td>
              <a href="{% url 'tasks:update' task.id%}">{% translate 'Edit' %}</a>
              <br>
              <a href="{% url 'tasks:delete' task.id %}">{% translate 'Delete' %}</a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>

{% endblock %}
      

task_manager/templates/tasks/task_form.html
{% extends "base.html" %}
{% load i18n %}
{% load django_bootstrap5 %}

{% block title %}
  {{ title }}
{% endblock %}

{% block main_classes %}container wrapper flex-grow-1{% endblock %}

{% block content %}
  <h1 class="my-4">
    {{ title }}
  </h1>

  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <div class="mb-3">
        <label class="form-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
        {{ field }}
        {% if field.help_text %}
          <div class="form-text">{{ field.help_text }}</div>
        {% endif %}
        {% if field.errors %}
          <div class="text-danger">{{ field.errors }}</div>
        {% endif %}
      </div>
    {% endfor %}
    <input class="btn btn-outline-success" type="submit" value="{{ button_name }}">
  </form>
{% endblock %}

task_manager/templates/tasks/update.html
{% extends "base.html" %}
{% load i18n %}
{% load django_bootstrap5 %}
{% block content %}
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="{% translate 'Update' %}">
</form>
{% endblock %}